CharacterBuilder.MVC/Controllers/WeaponController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CharacterBuilder.Models.Weapon;
using CharacterBuilder.Services.Weapon;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CharacterBuilder.MVC.Controllers
{
    public class WeaponController : Controller
    {
        private readonly ILogger<WeaponController> _logger;
        private readonly IWeaponService _weaponService;
        private readonly UserManager<IdentityUser<int>> _userManager;

        public WeaponController(ILogger<WeaponController> logger, IWeaponService weaponService, UserManager<IdentityUser<int>> userManager)
        {
            _logger = logger;
            _weaponService = weaponService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var allWeapons = await _weaponService.GetAllWeaponsAsync();
            return View(allWeapons);
        }
        [Authorize]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(WeaponCreate model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser is null)
            {
                ViewData["ErrorMsg"] = "invalid user";
                return View(model);
            }
            var weaponCreated = await _weaponService.CreateWeaponAsync(model,currentUser.Id);
            if (!weaponCreated)
            {
                ViewData["ErrorMsg"] = "Could not create weapon";
                return View(model);
            }
            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        public async Task<IActionResult> Update([FromRoute] int id)
        {
            var weaponToUpdate = await _weaponService.GetWeaponByIdAsync(id);
            if (weaponToUpdate is null)
                return RedirectToAction(nameof(Index));
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser is null || weaponToUpdate.CreatorId != currentUser.Id)
            {
                ViewData["ErrorMsg"] = "Unauthorized edit attempt. You shall not pass.";
                return RedirectToAction(nameof(Index));
            }
            var weaponEditModel = new WeaponEdit {
                Id = weaponToUpdate.Id,
                Name = weaponToUpdate.Name,
                LowAttackRange = weaponToUpdate.LowAttackRange,
                HighAttackRange = weaponToUpdate.HighAttackRange,
                LowThrownRange = weaponToUpdate.LowThrownRange,
                HighThrownRange = weaponToUpdate.HighThrownRange,
                AttackingStat = weaponToUpdate.AttackingStat,
                TargetStat = weaponToUpdate.TargetStat,
                IsTwoHanded = weaponToUpdate.IsTwoHanded,
                CreatorId = weaponToUpdate.CreatorId
            };
            return View(weaponEditModel);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Update(WeaponEdit model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser is null)
                return RedirectToAction(nameof(Index));
            var updatedSuccess = await _weaponService.UpdateWeaponAsync(model,currentUser.Id);
            if (!updatedSuccess)
                ViewData["ErrorMsg"] = "Could not update weapon";
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> ConfirmDelete([FromRoute]int id)
        {
            var weaponToDelete = await _weaponService.GetWeaponByIdAsync(id);
            if (weaponToDelete is null)
            {
                ViewData["ErrorMsg"] = "Invalid weapon request";
                return RedirectToAction(nameof(Index));
            }
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser is null || weaponToDelete.CreatorId != currentUser.Id)
            {
                ViewData["ErrorMsg"] = "Unauthorized delete attempt. You shall not pass.";
                return RedirectToAction(nameof(Index));
            }
            return View(weaponToDelete);
        }
        [Authorize]
        public async Task<IActionResult> Delete([FromRoute]int id)
        {
            var deleteSuccess = await _weaponService.DeleteWeaponAsync(id);
            if (!deleteSuccess)
            {
                ViewData["ErrorMsg"] = "Weapon could not be deleted";
            }
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

CharacterBuilder.MVC/Views/Weapon/ConfirmDelete.cshtml
@model CharacterBuilder.Models.Weapon.WeaponDetail

@{
    ViewData["Title"] = $"Delete {Model.Name}?";
}

<div class="container col-8">
    <div class="alert alert-danger" role="alert">
        Are you sure you wish to delete <strong>@Model.Name</strong>?
        This cannot be undone.
    </div>
    @Html.ActionLink("Delete","Delete",new {id = Model.Id}, new {Class="btn btn-danger"})
    @Html.ActionLink("Get me out of here!", "Index", new {id = @Model.Id}, new {Class="btn btn-primary"})
</div>

CharacterBuilder.MVC/Views/Weapon/Create.cshtml
@model CharacterBuilder.Models.Weapon.WeaponCreate

@{
    ViewData["Title"] = "Create Weapon";
}

<div class="container-fluid">
    <form asp-action="Create">
        <div class="form-group">
            @Html.DisplayNameFor(w => w.Name)
            @Html.TextBoxFor(w => w.Name, new {Class="form-control"})
            @Html.DisplayNameFor(w => w.IsTwoHanded)
            @Html.CheckBoxFor(w => w.IsTwoHanded, new {Class="form-check-input"})
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(w => w.LowAttackRange)
            @Html.TextBoxFor(w => w.LowAttackRange , new {Class="form-control"})
            @Html.DisplayNameFor(w => w.HighAttackRange)
            @Html.TextBoxFor(w => w.HighAttackRange , new {Class="form-control"})
            @Html.DisplayNameFor(w => w.LowThrownRange)
            @Html.TextBoxFor(w => w.LowThrownRange , new {Class="form-control"})
            @Html.DisplayNameFor(w => w.HighThrownRange)
            @Html.TextBoxFor(w => w.HighThrownRange , new {Class="form-control"})
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(w => w.AttackingStat)
            @Html.TextBoxFor(w => w.AttackingStat , new {Class="form-control"})
            @Html.DisplayNameFor(w => w.TargetStat)
            @Html.TextBoxFor(w => w.TargetStat , new {Class="form-control"})
        </div>
        <input class="btn btn-primary" type="submit" value="Create Weapon">
    </form>
</div>

CharacterBuilder.MVC/Views/Weapon/Index.cshtml
@model List<CharacterBuilder.Models.Weapon.WeaponListItem>

@{
    ViewData["Title"] = "All weapons";
}

<div class="container-fluid">
    <table class="table">
        <thead>
            <th>Name</th>
            <th>Low attack range</th>
            <th>High attack range</th>
            <th>Low Thrown range</th>
            <th>High Thrown range</th>
            <th>Attacking Stat</th>
            <th>Target Stat</th>
            <th>Is Two Handed</th>
            <th></th>
        </thead>
        <tbody>
            @foreach(var weapon in Model)
            {
                <tr>
                    <td>@weapon.Name</td>
                    <td>@weapon.LowAttackRange</td>
                    <td>@(weapon.HighAttackRange==null? "n/a" : weapon.HighAttackRange)</td>
                    <td>@(weapon.LowThrownRange==null? "n/a" : weapon.LowThrownRange)</td>
                    <td>@(weapon.HighThrownRange==null? "n/a" : weapon.HighThrownRange)</td>
                    <td>@weapon.AttackingStat</td>
                    <td>@weapon.TargetStat</td>
                    <td>@weapon.IsTwoHanded</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Update" asp-controller="Weapon" asp-route-id="@weapon.Id">Edit</a>
                        <a class="btn btn-danger" asp-action="ConfirmDelete" asp-controller="Weapon" asp-route-id="@weapon.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-primary" asp-action="Create" asp-controller="Weapon">Create a weapon</a>
</div>

CharacterBuilder.MVC/Views/Weapon/Update.cshtml
@model CharacterBuilder.Models.Weapon.WeaponEdit

@{
    ViewData["Title"] = "Edit Weapon";
}

<div class="container-fluid">
    <form asp-action="Update">
        <div class="form-group">
            @Html.HiddenFor(w => w.CreatorId)
            @Html.HiddenFor(w => w.Id)
            @Html.DisplayNameFor(w => w.Name)
            @Html.TextBoxFor(w => w.Name, new { Class="form-control"})
            <div class="form-check">
                @Html.DisplayNameFor(w => w.IsTwoHanded)
                @Html.CheckBoxFor(w => w.IsTwoHanded, new {Class="form-check-input" })
            </div>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(w => w.LowAttackRange)
            @Html.TextBoxFor(w => w.LowAttackRange , new {Class="form-control"})
            @Html.DisplayNameFor(w => w.HighAttackRange)
            @Html.TextBoxFor(w => w.HighAttackRange , new {Class="form-control"})
            @Html.DisplayNameFor(w => w.LowThrownRange)
            @Html.TextBoxFor(w => w.LowThrownRange , new {Class="form-control"})
            @Html.DisplayNameFor(w => w.HighThrownRange)
            @Html.TextBoxFor(w => w.HighThrownRange , new {Class="form-control"})
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(w => w.AttackingStat)
            @Html.TextBoxFor(w => w.AttackingStat , new {Class="form-control"})
            @Html.DisplayNameFor(w => w.TargetStat)
            @Html.TextBoxFor(w => w.TargetStat , new {Class="form-control"})
        </div>
        <input class="btn btn-primary" type="submit" value="Update Weapon">
    </form>
</div>