CharacterBuilder.MVC/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CharacterBuilder.Models.Campaign;
using CharacterBuilder.Models.CampaignPlayer;
using CharacterBuilder.Services.Campaign;
using CharacterBuilder.Services.CampaignPlayer;
using CharacterBuilder.Services.Character;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CharacterBuilder.MVC.Controllers
{
    [Authorize]
    public class CampaignController : Controller
    {
        private readonly ILogger<CampaignController> _logger;
        private readonly ICampaignService _campaignService;
        private readonly ICharacterService _characterService;
        private readonly ICampaignPlayerService _campaignPlayerService;
        private readonly UserManager<IdentityUser<int>> _userManager;

        public CampaignController(ILogger<CampaignController> logger, ICampaignService campaignService, ICharacterService characterService, ICampaignPlayerService campaignPlayerService, UserManager<IdentityUser<int>> userManager)
        {
            _logger = logger;
            _campaignService = campaignService;
            _characterService = characterService;
            _campaignPlayerService = campaignPlayerService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = 0;
            int.TryParse(_userManager.GetUserId(User), out userId);
            if (userId == 0)
                return RedirectToAction("Index","Home");
            var campaigns = await _campaignService.GetAllCampaignsByPlayerIdAsync(userId);
            return View(campaigns);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CampaignCreate model)
        {
            var userId = 0;
            int.TryParse(_userManager.GetUserId(User), out userId);
            if (userId == 0)
                return View(model);
            if (!ModelState.IsValid)
                return View(model);
            var campaignCreated = await _campaignService.CreateCampaignAsync(model, userId);
            if (!campaignCreated)
                return View(model);
            return RedirectToAction(nameof(Index), new {id=userId});
        }

        public async Task<IActionResult> Detail([FromRoute] int id)
        {
            var campaign = await _campaignService.GetCampaignByIdAsync(id);
            if (campaign is null)
                return RedirectToAction(nameof(Index));

            return View(campaign);
        }
        public async Task<IActionResult> AddPlayer([FromRoute]int id)
        {
            var campaign = await _campaignService.GetCampaignByIdAsync(id);
            if (campaign is null)
                return RedirectToAction(nameof(Index));
            var model = new CampaignPlayerCreate {
                CampaignId = id
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddPlayer([FromRoute]int id, string username)
        {
            var userToAdd = await _userManager.FindByEmailAsync(username);
            if (userToAdd is null)
                return RedirectToAction("Detail", new {id=id});
            
            var usersCampaigns = await _campaignPlayerService.GetPlayersByCampaignIdAsync(id);

            var userInCampaign = usersCampaigns.Where(c => c.UserName == userToAdd.UserName);
                if (userInCampaign.Count() > 0)
                    return RedirectToAction("Detail", new {id=id});
            
            var addedPlayer = await _campaignPlayerService
                .AddPlayerToCampaignAsync(new CampaignPlayerCreate 
                {
                    CampaignId = id,
                    PlayerId = userToAdd.Id
                });
            return RedirectToAction("Detail", new {id=id});
        }

        public async Task<IActionResult> RemovePlayer([FromRoute] int id, string username)
        {
            var campaign = await _campaignService.GetCampaignByIdAsync(id);
            if (campaign is null)
                return RedirectToAction(nameof(Index));

            var user = await _userManager.FindByNameAsync(username);
            if (user is null)
                return RedirectToAction(nameof(Index));

            var removeSuccess = await _campaignPlayerService.RemovePlayerFromCampaignAsync(user.Id,campaign.Id);
            
            return RedirectToAction("Detail", new {id=campaign.Id});
        }   

        public async Task<IActionResult> AddCharacter([FromRoute] int id)
        {
            var campaignId = id;
            var campaignExists = await _campaignService.GetCampaignByIdAsync(campaignId);
            if (campaignExists is null)
                return RedirectToAction(nameof(Index));

            var userId = 0;
            int.TryParse(_userManager.GetUserId(User), out userId);
            if (userId == 0)
                return RedirectToAction(nameof(Detail), new {id=id});

            var characters = await _characterService.GetAllUnusedCharactersByOwnerId(userId);
            ViewData["CampaignId"] = id;
            return View(characters);
        }
        [HttpPost]
        public async Task<IActionResult> AddCharacter(int characterId, [FromRoute]int id)
        {
            var updatedSuccess = await _characterService.AddCharacterToCampaignAsync(characterId, id);
            if (!updatedSuccess)
                return await AddCharacter(id);
            return RedirectToAction("Detail", new {id=id});
        }
        
        public async Task<IActionResult> RemoveCharacter([FromRoute]int id, int campaignId)
        {
            var currentUserId = 0;
            var validId = int.TryParse(_userManager.GetUserId(User), out currentUserId);
            if (!validId)
                return RedirectToAction(nameof(Index));

            var currentCharacter = await _characterService.GetCharacterById(id);
            if (currentCharacter is null || currentCharacter.OwnerId != currentUserId)
                return RedirectToAction(nameof(Index));

            var removedCampaignSuccess = await _characterService.RemoveCharacterFromCampaignAsync(id);

            return RedirectToAction("Detail", new {id=campaignId});
        }
        public async Task<IActionResult> Update([FromRoute] int id)
        {
            var campaign = await _campaignService.GetCampaignByIdAsync(id);
            if (campaign is null)
                return RedirectToAction(nameof(Index));
            var userId = 0;
            var validId = int.TryParse(_userManager.GetUserId(User), out userId);
            if (!validId)
                return RedirectToAction(nameof(Index));
            var currentUser = await _userManager.FindByIdAsync(userId.ToString());
            if (currentUser is null || currentUser.UserName != campaign.GameMasterName)
                return RedirectToAction(nameof(Index));
            var campaignEdit = new CampaignEdit {
                Id = campaign.Id,
                Name = campaign.Name,
                Description = campaign.Description
            };
            
            return View(campaignEdit);
        }
        [HttpPost]
        public async Task<IActionResult> Update(CampaignEdit model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var updateSuccess = await _campaignService.UpdateCampaignAsync(model);
            if (!updateSuccess)
                return View(model);
            return RedirectToAction("Detail", new {id=model.Id});
        }
        
        public async Task<IActionResult> ConfirmDelete([FromRoute]int id)
        {
            var userId = 0;
            int.TryParse(_userManager.GetUserId(User), out userId);

            var campaign = await _campaignService.GetCampaignByIdAsync(id);
            if(campaign is null)
                return RedirectToAction(nameof(Index));
            return View(campaign);
        }
        public async Task<IActionResult> Delete([FromRoute]int id)
        {
            var deletedSuccessfully = await _campaignService.DeleteCampaignAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

CharacterBuilder.MVC/Views/Campaign/AddCharacter.cshtml
@model List<CharacterBuilder.Models.Character.CharacterListItem>

@inject ICampaignService _campaignService;

@{
    int campaignId = 0;
    var validCampaign = int.TryParse(ViewData["CampaignId"].ToString(), out campaignId);
    var campaign = await _campaignService.GetCampaignByIdAsync(campaignId); 
}

<div class="container-fluid">
    <h1>Add character to campaign</h1>
    <form asp-action="AddCharacter" asp-route-campaignId="@campaignId">
        <div class="form-group col-md-6">
            <select class="form-select" name="characterId">
                @foreach(var character in Model)
                {
                    <option value=@character.Id>
                        @character.Name
                    </option>
                }
            </select>
        </div>
        <input class="btn btn-primary" type="submit" value="Add character to campaign">
    </form>
</div>

CharacterBuilder.MVC/Views/Campaign/AddPlayer.cshtml
@model CharacterBuilder.Models.CampaignPlayer.CampaignPlayerCreate
@{
    ViewData["Title"] = "Add a player to your campaign";
}

<div class="container-fluid">
    <h1>Add player to campaign</h1>
    <form asp-action="AddPlayer">
        @Html.Hidden("campaignId",@Model.CampaignId)
        <div class="form-group col-6">
            <label for="username">Player Name</label>
            <input class="form-control" name="username" placeholder="user name to add">
        </div>
        <input class="btn btn-primary" type="submit" value="Add Player">
    </form>
</div>

CharacterBuilder.MVC/Views/Campaign/ConfirmDelete.cshtml
@model CharacterBuilder.Models.Campaign.CampaignDetail

@{
    ViewData["Title"] = $"Details - {@Model.Name}";
}

<div class="container col-8">
    <div class="alert alert-danger" role="alert">
        Are you sure you wish to delete <strong>@Model.Name</strong>?
        This cannot be undone.
    </div>
    @Html.ActionLink("Delete","Delete",new {id = Model.Id}, new {Class="btn btn-danger"})
    @Html.ActionLink("Get me out of here!", "Detail", new {id = @Model.Id}, new {Class="btn btn-primary"})
</div>

CharacterBuilder.MVC/Views/Campaign/Create.cshtml
@model CharacterBuilder.Models.Campaign.CampaignCreate

@{
    ViewData["Title"] = "Create new Campaign";
}

<div class="container-fluid">
    <h1>New Campaign</h1>
    <form class="col-md-8" asp-action="Create">
        <div class="form-group">
            @Html.DisplayNameFor(c => c.Name)
            @Html.TextBoxFor(c => c.Name, new {Class="form-control"})
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c=>c.Description)
            @Html.TextAreaFor(c => c.Description, new {Class="form-control", Rows=6})
        </div>
        <input class="btn btn-primary" type="submit" value="Create">
    </form>
</div>

CharacterBuilder.MVC/Views/Campaign/Detail.cshtml
@model CharacterBuilder.Models.Campaign.CampaignDetail

@{
    ViewData["Title"] = $"{@Model.Name} - Campaign Details";
}

<div class="container-fluid">
    <h1>@Model.Name</h1>
    <p class="col-8 pb-5">@Model.Description</p>
    <div class="container">
        <h2>Players</h2>
        @if (Model.Players.Count == 0)
        {
            <p>This adventure could use some adventurers. Add players by username with the button below.</p>
        }
        else {
        <table class="table">
            <tbody>
                    @foreach(var player in Model.Players)
                    {
                        <tr>
                            <td>@player.UserName</td>
                            <td>
                                @Model.Characters.Where(c => c.OwnerName == player.UserName).FirstOrDefault()?.Name
                            </td>
                            <td>
                                @Html.ActionLink("Leave campaign", "RemovePlayer", new {id=Model.Id, username=player.UserName})
                            </td>
                        </tr>
                    }
            </tbody>
        </table>
        }
    @Html.ActionLink("Add a Player", "AddPlayer", new {id=@Model.Id}, new {Class="btn btn-primary"})
    </div>
    <div class="container pb-5">
        <h2>Characters</h2>
        @if (Model.Characters.Count == 0)
        {
            <p>Your story needs characters. Add a character with the button below</p>
        }
        else
        {
            <table class="table table-striped">
                <thead>
                    <th>Owner Name</th>
                    <th>Character Name</th>
                    <th>Character Level</th>
                    <th></th>
                </thead>
                <tbody>
                    @foreach(var character in Model.Characters)
                    {
                        <tr>
                            <td>@character.OwnerName</td>
                            <td>@character.Name</td>
                            <td>@character.Level</td>
                            <td>@Html.ActionLink("Remove","RemoveCharacter", new {id=@character.Id, campaignId=@Model.Id}, new {Class="btn btn-danger-sm"})</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        @Html.ActionLink("Add a character", "AddCharacter",new {id=@Model.Id}, new {Class="btn btn-primary"})
    </div>
    @Html.ActionLink("Edit Campaign", "Update", new {id=@Model.Id}, new {Class="btn btn-primary"})
    @Html.ActionLink("Delete Campaign","ConfirmDelete", new {id=@Model.Id},new {Class="btn btn-danger"})
</div>

CharacterBuilder.MVC/Views/Campaign/Index.cshtml
@model List<CharacterBuilder.Models.Campaign.CampaignListItem>

@{
    ViewData["Title"] = "Your campaigns";
}
<div class="container-fluid">
    @if (Model.Count() == 0)
    {
        <h2>You do not have any campaigns</h2>
        <p>Click the button below to create a new campaign</p>
    }
    else
    {
        <div class="d-flex flex-md-row flex-wrap gap-2 pb-2 pt-2">
    
            @foreach(var campaign in Model)
            {
                <div class="card flex-grow-1 flex-md-grow-0" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@campaign.Name</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Game Master: @campaign.GameMasterName</h6>
                        <a class="card-link" asp-controller="Campaign" asp-action="Detail" asp-route-id="@campaign.Id">Campaign Details</a>
                    </div>
                </div>
            }
        </div>
    }
    <a class="btn btn-primary" asp-controller="Campaign" asp-action="Create">Create New Campaign</a>
</div>

CharacterBuilder.MVC/Views/Campaign/Update.cshtml
@model CharacterBuilder.Models.Campaign.CampaignEdit

@{
    ViewData["Title"] = "Edit campaign";
}

<div class="container-fluid">
    <form asp-action="Update" asp-route-id="@Model.Id">
        @Html.Hidden("Id", @Model.Id)
        <div class="form-group">
            @Html.DisplayNameFor(c => c.Name)
            @Html.TextBoxFor(c => c.Name, new {Class="form-control"})
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.Description);
            @Html.TextAreaFor(c => c.Description, new {Class="form-control", Rows=6})
        </div>
        <input class="btn btn-primary" type="submit" value="Update Campaign">
    </form>
</div>