CharacterBuilder.MVC/Controllers/CharacterController.cs
using System.Security.Claims;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CharacterBuilder.Services.Character;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using CharacterBuilder.Models.Character;
using CharacterBuilder.Services.InventorySlots;
using CharacterBuilder.Services.Item;
using CharacterBuilder.Services.Weapon;

namespace CharacterBuilder.MVC.Controllers
{
    [Authorize]
    public class CharacterController : Controller
    {
        private readonly ILogger<CharacterController> _logger;
        private readonly ICharacterService _characterService;
        private readonly UserManager<IdentityUser<int>> _userManager;
        private readonly IItemService _itemService;
        private readonly IWeaponService _weaponService;

        public CharacterController(ILogger<CharacterController> logger, ICharacterService characterService, UserManager<IdentityUser<int>> userManager, IItemService itemService, IWeaponService weaponService)
        {
            _logger = logger;
            _characterService = characterService;
            _userManager = userManager;
            _itemService = itemService;
            _weaponService = weaponService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ClaimsPrincipal currentUser = this.User;
            int userId = 0;
            var validId = int.TryParse( _userManager.GetUserId(currentUser), out userId);
            
            if (!validId)
            {
                ViewBag["ErrorMsg"] = "Invalid user ID";
                return RedirectToAction(nameof(Error));
            }
                
            var characters = await _characterService.GetAllCharactersByOwnerId(userId);
            return View(characters);
        }
        
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CharacterCreate model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["ErrorMsg"] = "Invalid data entered";
                return View(model);
            }
            
            var currentUser = this.User;
            var userId = 0;
            var validId = int.TryParse(_userManager.GetUserId(currentUser), out userId);
            if (!validId)
            {
                ViewData["ErrorMsg"] = "Invalid user ID. Character not created.";
                return View(model);
            }
            var characterCreated = await _characterService.CreateCharacterAsync(model, userId);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Detail([FromRoute]int id)
        {
            var character = await _characterService.GetCharacterById(id);
            if (character is null)
            {
                ViewData["ErrorMsg"] = "Invalid character ID";
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AllItems = await _itemService.GetAllItemsAsync();
            ViewBag.AllWeapons = await _weaponService.GetAllWeaponsAsync();
            
            return View(character);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CharacterDetail model) {
            if (!ModelState.IsValid)
            {
                ViewData["ErrorMsg"] = "Invalid inputs";
                return await Detail(model.Id);
            }
            var existingCharacter = await _characterService.GetCharacterById(model.Id);
            var currentUser = await _userManager.GetUserAsync(User);
            if (existingCharacter is null)
            {
                ViewData["ErrorMsg"] = "Character does not exist";
                return RedirectToAction(nameof(Index));
            } 
            if(existingCharacter.OwnerName != currentUser.UserName)
            {
                ViewData["ErrorMsg"] = "Unauthorized access of character";
                return RedirectToAction(nameof(Index));
            }

            var updateModel = new CharacterEdit {
                Id = model.Id,
                CampaignId = model.CampaignId,
                OwnerId = currentUser.Id,
                Name = model.Name,
                Height = model.Height,
                Weight = model.Weight,
                Age = model.Age,
                Level = model.Level,
                MindScore = model.MindScore,
                BodyScore = model.BodyScore,
                ResilienceScore = model.ResilienceScore,
                SoulScore = model.SoulScore,
                MovementScore = model.MovementScore,
                CurrentHp = model.CurrentHp,
                CurrentTalentPoints = model.CurrentTalentPoints,
                CurrentMovementPoints = model.CurrentMovementPoints,
                WeaponProficiencies = model.WeaponProficiencies
            };
            var successfullyUpdated = await _characterService.UpdateCharacterAsync(updateModel);
            if (!successfullyUpdated)
                ViewData["ErrorMsg"] = "Character not updated";
            return RedirectToAction(nameof(Detail),new {id = updateModel.Id});
        }

        public async Task<IActionResult> ConfirmDelete([FromRoute]int id)
        {
            var character = await _characterService.GetCharacterById(id);
            return View(character);
        }
        
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            var deleteSuccess = await _characterService.DeleteCharacterAsync(id);
            if (!deleteSuccess)
            {
                ViewData["ErrorMsg"] = "Character could not be deleted";
            }
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

CharacterBuilder.MVC/Controllers/InventorySlotController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CharacterBuilder.Models.CharacterInventorySlot;
using CharacterBuilder.Services.InventorySlots;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CharacterBuilder.MVC.Controllers
{
    public class InventorySlotController : Controller
    {
        private readonly ILogger<InventorySlotController> _logger;
        private readonly IInventorySlotsService _inventorySlotService;

        public InventorySlotController(ILogger<InventorySlotController> logger, IInventorySlotsService inventorySlotService)
        {
            _logger = logger;
            _inventorySlotService = inventorySlotService;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(InventorySlotCreate model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["ErrorMsg"] = "Invalid Model";
            }
            var slotCreateSuccess = await _inventorySlotService.CreateInventorySlotAsync(model);
            if (!slotCreateSuccess)
                ViewData["ErrorMsg"] = "Could not create inventory slot";

            return RedirectToAction("Detail", "Character", new {id=model.CharacterId});
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Update(InventorySlotEdit model)
        {
            if (ModelState.IsValid)
            {
                var updateSuccess = await _inventorySlotService.UpdateInventorySlotAsync(model);
                if (!updateSuccess)
                    ViewData["ErrorMsg"] = "Error updating inventory slot";
            }
            return RedirectToAction("Detail", "Character", new {id=model.CharacterId});
        }

        [Authorize]
        public async Task<IActionResult> Delete([FromRoute] int id,int characterId)
        {
            var deleteSuccess = await _inventorySlotService.DeleteInventorySlotAsync(id);
            if (!deleteSuccess)
                ViewData["ErrorMsg"] = "Could not delete item slot";
            return RedirectToAction("Detail", "Character", new {id=characterId});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

CharacterBuilder.MVC/Views/Character/ConfirmDelete.cshtml
@model CharacterBuilder.Models.Character.CharacterDetail

@{
    ViewData["Title"] = $"Details - {@Model.Name}";
}

<div class="container col-8">
    <div class="alert alert-danger" role="alert">
        Are you sure you wish to delete <strong>@Model.Name</strong>?
        This cannot be undone.
    </div>
    @Html.ActionLink("Delete","Delete",new {id = Model.Id}, new {Class="btn btn-danger"})
    @Html.ActionLink("Get me out of here!", "Detail", new {id = @Model.Id}, new {Class="btn btn-primary"})
</div>

CharacterBuilder.MVC/Views/Character/Create.cshtml
@model CharacterBuilder.Models.Character.CharacterCreate

@{
    ViewData["Title"] = "Create a Character";
}

<div class="container">
    <form asp-action="Create">
        <div class="form-group">
            @Html.DisplayNameFor(c => c.Name)
            @Html.TextBoxFor(c => c.Name, new {Class="form-control"})
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.Height)
            @Html.TextBoxFor(c => c.Height, new {Class="form-control"})
            <span asp-validation-for="Height"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.Weight)
            @Html.TextBoxFor(c => c.Weight, new {Class="form-control"})
            <span asp-validation-for="Weight"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.Age)
            @Html.TextBoxFor(c => c.Age, new {Class="form-control"})
            <span asp-validation-for="Age"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c=>c.MindScore)
            @Html.TextBoxFor(c=>c.MindScore, new {Class="form-control"})
            <span asp-validation-for="MindScore"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.BodyScore)
            @Html.TextBoxFor(c => c.BodyScore, new {Class="form-control"})
            <span asp-validation-for="BodyScore"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.ResilienceScore)
            @Html.TextBoxFor(c => c.ResilienceScore, new {Class="form-control"})
            <span asp-validation-for="ResilienceScore"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.SoulScore)
            @Html.TextBoxFor(c => c.SoulScore, new {Class="form-control"})
            <span asp-validation-for="SoulScore"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.MovementScore)
            @Html.TextBoxFor(c => c.MovementScore, new {Class="form-control"})
            <span asp-validation-for="MovementScore"></span>
        </div>
        <div class="form-group">
            @Html.DisplayNameFor(c => c.WeaponProficiencies)
            @Html.TextAreaFor(c => c.WeaponProficiencies, new {Class="form-control"})
            <span asp-validation-for="WeaponProficiencies"></span>
        </div>
        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Create Character">
        </div>
    </form>
</div>

CharacterBuilder.MVC/Views/Character/Detail.cshtml
@model CharacterBuilder.Models.Character.CharacterDetail

@{
    ViewData["Title"] = $"Details - {@Model.Name}";
    ViewData["CharacterID"] = Model.Id;
}

<div class="container col-10">
    <form class="pb-3" asp-action="Update">
        <div class="d-flex gap-2 pb-4">
            <div class="form-group flex-fill">
                @Html.DisplayNameFor(c => c.Name)
                @Html.TextBoxFor(c => c.Name, new {Class="form-control-lg"})
                <span asp-validation-for="Name"></span>
            </div>
            <div class="form-group flex-fill">
                @Html.HiddenFor(c => c.OwnerId)
                @Html.HiddenFor(c => c.OwnerName)
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(c => c.Level)
                @Html.TextBoxFor(c => c.Level, new {type="number", Class="form-control"})
                <span asp-validation-for="Level"></span>
            </div>
        </div>
        <div class="d-flex gap-2 pb-4">
            <div class="form-group flex-fill">
                @Html.HiddenFor(c => c.Id)
                @Html.DisplayNameFor(c => c.OwnerName)
                @Html.DisplayTextFor(c => c.OwnerName)
            </div>
        </div>
        
    @if (Model.CampaignId is not null && Model.CampaignName is not null)
    {
        <div class="form-group pb-2">
            @Html.DisplayNameFor(c => c.CampaignName)
            @Html.DisplayTextFor(c => c.CampaignName)
        </div>
    }
        <div class="d-flex flex-row justify-content-evenly pb-2">
            <div class="form-group flex-col">
                @Html.DisplayNameFor(c => c.Height)
                @Html.TextBoxFor(c => c.Height, new {Class="form-control flex-grow-1"})
                <span asp-validation-for="Height"></span>
            </div>
            <div class="form-group flex-col">
                @Html.DisplayNameFor(c => c.Weight)
                @Html.TextBoxFor(c => c.Weight, new {Class="form-control flex-grow-1"})
                <span asp-validation-for="Weight"></span>
            </div>
            <div class="form-group flex-col">
                @Html.DisplayNameFor(c => c.Age)
                @Html.TextBoxFor(c => c.Age, new {Class="form-control flex-grow-1"})
                <span asp-validation-for="Age"></span>
            </div>
        </div>
        <div class="d-flex justify-content-evenly pb-4">
            <div class="form-group">
                @Html.DisplayNameFor(c=>c.MindScore)
                @Html.TextBoxFor(c=>c.MindScore, new {type="number",Class="form-control"})
                <span asp-validation-for="MindScore"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(c => c.BodyScore)
                @Html.TextBoxFor(c => c.BodyScore, new {type="number",Class="form-control"})
                <span asp-validation-for="BodyScore"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(c => c.ResilienceScore)
                @Html.TextBoxFor(c => c.ResilienceScore, new {type="number",Class="form-control"})
                <span asp-validation-for="ResilienceScore"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(c => c.SoulScore)
                @Html.TextBoxFor(c => c.SoulScore, new {type="number",Class="form-control"})
                <span asp-validation-for="SoulScore"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(c => c.MovementScore)
                @Html.TextBoxFor(c => c.MovementScore, new {type="number",Class="form-control"})
                @Html.DisplayNameFor(c => c.CurrentMovementPoints)
                @Html.TextBoxFor(c => c.CurrentMovementPoints, new {type="number", Class="form-control"})
                <span asp-validation-for="MovementScore"></span>
            </div>
        </div>
        <div class="form-group">
            @* Add HP display stuff *@
            @Html.DisplayNameFor(c => c.CurrentHp)
            @Html.TextBoxFor(c => c.CurrentHp, new {type="number", Class="form-control"})
            @* Add Talent Point display stuff *@
            @Html.DisplayNameFor(c => c.CurrentTalentPoints)
            @Html.TextBoxFor(c => c.CurrentTalentPoints, new {type="number", Class="form-control"})
        </div>

        <div class="form-group pb-2">
            @Html.DisplayNameFor(c => c.WeaponProficiencies)
            @Html.TextAreaFor(c => c.WeaponProficiencies, new {rows="6",Class="form-control"})
            <span asp-validation-for="WeaponProficiencies"></span>
        </div>
        <div class="form-group h-auto">
            <input class="btn btn-primary" type="submit" value="Update Character Stats">
        </div>
    </form>
    <div class="container-fluid">
        <h2>Weapons</h2>
        <table class="table table-striped pb-4">
            <thead>
                <th>Name</th>
                <th>Low attack range</th>
                <th>High attack range</th>
                <th>Low Thrown range</th>
                <th>High Thrown range</th>
                <th>Attacking Stat</th>
                <th>Target Stat</th>
                <th>Is Two Handed</th>
                <th>Item Count</th>
                <th></th>
            </thead>
            <tbody>
                @foreach(var weapon in Model.Weapons)
                {
                    <tr>
                        <td>@weapon.Name</td>
                        <td>@weapon.LowAttackRange</td>
                        <td>@(weapon.HighAttackRange==null? "n/a" : weapon.HighAttackRange)</td>
                        <td>@(weapon.LowThrownRange==null? "n/a" : weapon.LowThrownRange)</td>
                        <td>@(weapon.HighThrownRange==null? "n/a" : weapon.HighThrownRange)</td>
                        <td>@weapon.AttackingStat</td>
                        <td>@weapon.TargetStat</td>
                        <td>@weapon.IsTwoHanded</td>
                        <td>
                            <form asp-controller="InventorySlot" asp-action="Update">
                                @Html.Hidden("SlotId",@weapon.SlotId)
                                @Html.Hidden("CharacterId",Model.Id)
                                <input class="col-2 form-control" name="ItemCount" type="number" value="@weapon.ItemCount">
                                <input class="btn btn-primary btn-sm" type="submit" value="Save Changes">
                            </form>
                        </td>
                        <td>
                            <a class="btn btn-danger" asp-action="Delete" asp-controller="InventorySlot" asp-route-id="@weapon.SlotId" asp-route-characterId="@Model.Id">Remove</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        
        
        <form class="row g-3 pb-5 d-flex justify-content-end" id="WeaponAddForm" asp-controller="InventorySlot" asp-action="Create">
            @Html.Hidden("CharacterId", Model.Id)
            <div class="col-8 form-group row">
                <div class="col-6">
                    <label>Add a weapon: </label>
                    <select class="form-select form-select-sm" name="WeaponId">
                    @foreach(var weapon in ViewBag.AllWeapons)
                    {
                        <option value="@weapon.Id">
                            @weapon.Name
                        </option>
                    }
                    </select>
                </div>
                <div class="form-group col-3">
                    <label for="ItemCount">Item Count</label>
                    <input type="number" name="ItemCount" value="1" class="form-control form-control-sm">
                </div>
                <div class="col-3 d-flex flex-col">
                    <input type="submit" value="Add weapon" class="btn btn-outline-primary btn-sm align-self-end">
                </div>
            </div>
        </form>
        <h2>Items</h2>
        <table class="table table-striped pb-3">
            <thead>
                <th>Name</th>
                <th>Description</th>
                <th>Item Count</th>
            </thead>
            <tbody>
                @foreach(var item in Model.Items)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td>
                            <form asp-controller="InventorySlot" asp-action="Update">
                                @Html.Hidden("SlotId",@item.SlotId)
                                @Html.Hidden("CharacterId",Model.Id)
                                <input class="col-2 form-control" name="ItemCount" type="number" value="@item.ItemCount">
                                <input class="btn btn-primary btn-sm" type="submit" value="Save Changes">
                            </form>
                        </td>
                        <td><a class="btn btn-danger" asp-action="Delete" asp-controller="InventorySlot" asp-route-id="@item.SlotId" asp-route-characterId="@Model.Id">Remove</a></td>
                    </tr>
                }
            </tbody>
        </table>
        <form class="row g-3 pb-5 d-flex justify-content-end" id="ItemAddForm" asp-controller="InventorySlot" asp-action="Create">
            @Html.Hidden("CharacterId", Model.Id)
            <div class="col-8 form-group row">
                <div class="col-6">
                    <label>Add an item: </label>
                    <select class="form-select form-select-sm" name="ItemId">
                    @foreach(var item in ViewBag.AllItems)
                    {
                        <option value="@item.Id">
                            @item.Name
                        </option>
                    }
                    </select>
                </div>
                <div class="form-group col-3">
                    <label for="ItemCount">Item Count</label>
                    <input type="number" name="ItemCount" value="1" class="form-control form-control-sm">
                </div>
                <div class="col-3 d-flex flex-col">
                    <input type="submit" value="Add item" class="btn btn-outline-primary btn-sm align-self-end">
                </div>
            </div>
        </form>
    </div>
    @Html.ActionLink($"Delete {@Model.Name}","ConfirmDelete",new {id = Model.Id}, new {Class="btn btn-danger"})
</div>

CharacterBuilder.MVC/Views/Character/Index.cshtml
@model IEnumerable<CharacterListItem>

@{
    ViewData["Title"] = "Your Characters";
}

<div class="container-fluid">
    @if (ViewData["ErrorMsg"] is not null)
    {
        <div class="alert alert-danger" role="alert">
            @ViewData["ErrorMsg"]
        </div>
    }
    <h1>Your Characters</h1>
    @if (Model.Count() == 0)
    {
        <h2>You do not have any characters</h2>
        <p>Click the button below to create a new adventurer</p>
    }
    else
    {
        <div class="d-flex flex-md-row flex-wrap gap-2 pb-2 pt-2">

            @foreach(var character in Model)
            {
                <div class="card flex-grow-1 flex-md-grow-0" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@character.Name</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Level @character.Level</h6>
                        @* <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> *@
                        <a class="card-link" asp-controller="Character" asp-action="Detail" asp-route-id="@character.Id">Character Details</a>
                    </div>
                </div>
            }
        </div>
    }
    <a class="btn btn-primary" asp-controller="Character" asp-action="Create">Create New Character</a>
</div>